#!/bin/bash
echo "Ì¥ç Checking GitHub Actions workflow status..."
echo ""
echo "Ì≥ã Go to: https://github.com/ductoanoxo/FOODFAST/actions"
echo ""
echo "‚úÖ Your workflows:"
echo "1. Docker Build and Push (triggers on push to main)"
echo "2. Deploy to EKS (auto-runs after Docker build)"
echo ""
echo "Ì¥ë Required GitHub Secrets:"
echo "- EKS_SSH_KEY (SSH private key)"
echo "- EKS_SERVER_HOST (IP: 100.25.98.10)"
echo "- EKS_SERVER_USER (ubuntu)"
echo "- GHCR_TOKEN"
echo "- MONGO_URI"
echo "- JWT_SECRET"
echo "- JWT_EXPIRE"
echo "- CLOUDINARY_CLOUD_NAME"
echo "- CLOUDINARY_API_KEY"
echo "- CLOUDINARY_API_SECRET"
