# Nixpacks Plan
[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm install',
  'cd server_app && npm install --production=false'
]

[phases.build]

[start]
cmd = 'cd server_app && npm start'
